// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdhcgjfnkdfdxpuieqsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkaGNnamZua2RmZHhwdWllcXNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NDk5NzQsImV4cCI6MjA1MjMyNTk3NH0.cBR7lrf9GKXfAxjE112I63HmiH26vX6FloAIrYU8sic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);